MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101-GN"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STRIDE_IN_1X1: False
    TRANS_FUNC: "BottleneckWithGN"
    STEM_FUNC: "StemWithGN"
  FPN:
    USE_GN: True
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    POST_NMS_TOP_N_TRAIN: 1000
    PRE_NMS_TOP_N_TEST: 30000
    POST_NMS_TOP_N_TEST: 15000
    FPN_POST_NMS_TOP_N_TEST: 8000
  ROI_HEADS:
    USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 512
    POSITIVE_FRACTION: 0.25
    DETECTIONS_PER_IMG: 8000
  ROI_BOX_HEAD:
    USE_GN: True # use GN for bbox head
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 2
  ROI_MASK_HEAD:
    USE_GN: True # use GN for mask head
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    CONV_LAYERS: (256, 256, 256, 256)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
  PANOPTIC:
    PS_ON: True
    SEM_PATH: "./datasets/fluo2tcga/semgt"
    USE_GN: True
  DOMAIN_ADAPTION:
    ENABLE_DA: True
    ENABLE_SEMDA: True
    SEM_TYPE: 'RES4'   # RES4 OR CNN6
    ENABLE_INSDA: True
    ENABLE_IMGDA: True
    LOSS_AVG: True
    MI_MAX: True
    FEATURE_CHANNEL: 64
DATASETS:
  TRAIN_SOURCE: ("cell_fluo2tcga_syn_train",)
  TRAIN_TARGET: ("cell_tcga",)
  TEST: ("cell_tcga",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  # Assume 1 gpus
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (16000, 24000)
  MAX_ITER: 24000
  IMS_PER_BATCH: 1
  EPOCH_PERIOD: 2400
  CHECKPOINT_PERIOD: 30000
TEST:
  IMS_PER_BATCH: 1
INPUT:
  MAX_SIZE_TRAIN: 256
  MAX_SIZE_TEST: 256
  PIXEL_MEAN: [128.0, 128.0, 128.0]
  HORIZONTAL_FLIP_PROB_TRAIN: 0.5
  VERTICAL_FLIP_PROB_TRAIN: 0.5
